[package]
name = "convlint"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.3", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing"] }
derive_more = { version = "2.1.1", features = ["display"] }
gix = "0.86.0"
gix-object = "0.63.0"
owo-colors = "4.3.0"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"
toml = "1.1.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.27.0"
